spring:
  application:
    name: owo-spring-proxy-service-v2
  mvc:
    charset: UTF-8
  web:
    resources:
      add-mappings: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.gongroin.owouserservice: DEBUG
    org.springframework.transaction: DEBUG

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true